### ISSUE TITLE
GitHub actions for deployment of opensidewalkmap_beta

### ISSUE THREAD

**Issue by fititnt** [kauevestena/osm_sidewalkreator#8]
Hello. The https://github.com/fititnt/opensidewalkmap_beta seems working fine. Then maybe consider deploy on  https://github.com/kauevestena/opensidewalkmap_beta ?

**Comment by kauevestena** [comment]
Of course man, I'm need to return to working on this project, and now I can, because now my phd has calmed down =D

I just need to think about the best architecture to develop the global phase:

- Or setting this one as a template and the codebase shall be updated by wgets
- Or by forking with the data on the gitignore (but I'm not sure if this will work)

**Comment by kauevestena** [comment]
Just now I've noted that we are in the other repo!!
